export const STATUS = Object.freeze({
  IDLE: 'idle',
  RUNNING: 'running',
  STOPPED: 'stopped',
  COMPLETED: 'completed',
  BLOCKED: 'blocked',
  ERROR: 'error'
});

export const ERROR_CODES = Object.freeze({
  UNSUPPORTED_PAGE: 'UNSUPPORTED_PAGE',
  KEYWORD_NOT_FOUND: 'KEYWORD_NOT_FOUND',
  RESULT_AREA_NOT_FOUND: 'RESULT_AREA_NOT_FOUND',
  RESULT_PARSE_FAILED: 'RESULT_PARSE_FAILED',
  NEXT_URL_NOT_FOUND: 'NEXT_URL_NOT_FOUND',
  NEXT_URL_UNCERTAIN: 'NEXT_URL_UNCERTAIN',
  NETWORK_ERROR: 'NETWORK_ERROR',
  BLOCKED_REQUEST: 'BLOCKED_REQUEST',
  CAPTCHA_SUSPECTED: 'CAPTCHA_SUSPECTED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  USER_STOPPED: 'USER_STOPPED',
  MAX_RESULTS_REACHED: 'MAX_RESULTS_REACHED',
  COMPLETED: 'COMPLETED'
});

export function makeError(code, message, details = {}) {
  return { code, message, details };
}
